# Areeba Ayaz
# 20I-0460
# AI-K

In [33]:
import numpy as np
import pandas as pd
import math
from itertools import combinations

# Bonus Task
### A friend of yours has just opened a pizza shop and he doesn’t want to you come there fearing you would eat for free. Somehow you sneak in the shop and you order an 8 inch pizza , your friend tells you that he doesn’t have an 8 inch pizza but he can give you two 5 inch ones at the same price with the exact same things. As a statistician, should you be taking that deal? Is that beneficial for you or not? Give statistical reasoning.

In [34]:
#calculating areas of both the pizzas
#area = pi.r^2

#8-inch radius = 4
e = math.pi * (4**2)
e = round(e,2)
print("Area of the 8 inch pizza is:\n", e)

print("-------------------")

#5-inch radius = 2.5
r = 5/2
f = math.pi * (r**2)
f = f * 2 #of 2 pizzas
f = round(f,2)
print("Area of the two 5 inch pizzas is:\n", f)

Area of the 8 inch pizza is:
 50.27
-------------------
Area of the two 5 inch pizzas is:
 39.27


#### It would not be better to get 2 5-inch pizzas, as the area is smaller than that of the 8-inch pizza

# Task01
### You and your friend are standing in front of a magician and he has a basket with 6 white, 4 red and 5 blue balls, each time the magician draws 3 balls and asks you to predict what would be the color of the balls. If you predict correctly the magician loses the game and you win. Since you have become a statistician after doing the ML assignment, what should be the optimal color scheme of the balls that you would propose in order to win the game?

In [35]:
white = ['W', 'W', 'W', 'W', 'W', 'W'] #6 white balls
blue = ['B', 'B', 'B', 'B', 'B'] #5 blue balls
red = ['R', 'R', 'R', 'R'] #4 red balls

balls = white
#balls.append(blue)
balls.extend(blue)
balls.extend(red)
print(len(balls))
print("------------------")
balls

15
------------------


['W', 'W', 'W', 'W', 'W', 'W', 'B', 'B', 'B', 'B', 'B', 'R', 'R', 'R', 'R']

In [36]:
#should have 455 possible combinations
comb = combinations(balls,3) #3 balls each time
c =[]

for i in comb:
    c.append(i)

#print(c)
#to check
len(c)

unique =set(combinations(balls,3)) #unique combinations
unique = set(uniqueCombinations)

u =list(uniqueCombinations)
u

[('W', 'W', 'W'),
 ('B', 'R', 'R'),
 ('W', 'W', 'B'),
 ('W', 'B', 'R'),
 ('W', 'W', 'R'),
 ('W', 'B', 'B'),
 ('B', 'B', 'R'),
 ('W', 'R', 'R'),
 ('B', 'B', 'B'),
 ('R', 'R', 'R')]

In [37]:
size =(len(u))
print(size)

arr = [0]*size
#print(arr)

for i, j in enumerate(u):
    arr[i]= c.count(j)

for index, a in enumerate(arr):
    if a == max(arr):
        break
    print('Combinations:',a, '\nProbability:', a/len(c))
    print("-----------------------------")

10
Combinations: 20 
Probability: 0.04395604395604396
-----------------------------
Combinations: 30 
Probability: 0.06593406593406594
-----------------------------
Combinations: 75 
Probability: 0.16483516483516483
-----------------------------


# Task 02

In [41]:
df = pd.read_csv('Iris.csv')
df.drop('Id',axis=1,inplace = True)
df.columns

df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [44]:
u = df['Species'].unique()

df1= df.drop('Species', axis = 1)
nu = df1.to_numpy() 

print(nu) 

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [71]:
#finding covarinace
co = []
ind = df['Species']
for i in u:
    co.append(df[ind == i].cov())
    
print ("Covarinace:\n",co)
print("-------------------------------------")
print("-------------------------------------")
co2 = np.array(co)
for a in range(0,3):
    for b in range(0,4):
        for c in range(0,4):
            if c != b:
                co2[a][c][b] = 0             
print("Covarince 2:\n",co2)

Covarinace:
 [               SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
SepalLengthCm       0.124249      0.100298       0.016139      0.010547
SepalWidthCm        0.100298      0.145180       0.011682      0.011437
PetalLengthCm       0.016139      0.011682       0.030106      0.005698
PetalWidthCm        0.010547      0.011437       0.005698      0.011494,                SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
SepalLengthCm       0.266433      0.085184       0.182898      0.055780
SepalWidthCm        0.085184      0.098469       0.082653      0.041204
PetalLengthCm       0.182898      0.082653       0.220816      0.073102
PetalWidthCm        0.055780      0.041204       0.073102      0.039106,                SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
SepalLengthCm       0.404343      0.093763       0.303290      0.049094
SepalWidthCm        0.093763      0.104004       0.071380      0.047629
PetalLengthCm       0.303290      0.071380      

In [72]:
from numpy import linalg as LA
det = LA.det(co2)
print("Determinant function:\n",det)

print("-------------------------------")

inverse= LA.inv(co2)
print("Inverse:\n",inverse)

Determinant function:
 [6.24194290e-06 2.26550291e-04 9.66211009e-04]
-------------------------------
Inverse:
 [[[ 8.04835584  0.          0.          0.        ]
  [ 0.          6.88802047  0.          0.        ]
  [ 0.          0.         33.21583514  0.        ]
  [ 0.          0.          0.         87.00284091]]

 [[ 3.75329371  0.          0.          0.        ]
  [ 0.         10.15544041  0.          0.        ]
  [ 0.          0.          4.52865065  0.        ]
  [ 0.          0.          0.         25.57144348]]

 [[ 2.47314867  0.          0.          0.        ]
  [ 0.          9.61500726  0.          0.        ]
  [ 0.          0.          3.28312607  0.        ]
  [ 0.          0.          0.         13.2568584 ]]]


# Task 03

In [73]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

In [74]:
df = pd.read_csv("Iris.csv")
df = df.drop('Id' , axis=1)
labels = df['Species']
le = LabelEncoder()
X = df.drop("Species", axis = 1)
y = le.fit_transform(labels)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 52)

In [75]:
clf1 = GaussianNB()
clf1.fit(X_train, y_train)
predict = clf1.predict(X_test)
score = clf1.score(X_test,y_test)
print("Score:\n",score)

Score:
 0.9111111111111111


In [76]:
t = np.array(X_test)
print(t)

[[5.  3.5 1.6 0.6]
 [4.9 3.1 1.5 0.1]
 [6.8 3.2 5.9 2.3]
 [6.7 3.  5.2 2.3]
 [7.3 2.9 6.3 1.8]
 [6.9 3.1 4.9 1.5]
 [5.  2.  3.5 1. ]
 [4.5 2.3 1.3 0.3]
 [7.7 2.8 6.7 2. ]
 [7.9 3.8 6.4 2. ]
 [6.7 3.3 5.7 2.1]
 [6.5 3.  5.8 2.2]
 [6.  2.7 5.1 1.6]
 [4.6 3.1 1.5 0.2]
 [7.4 2.8 6.1 1.9]
 [7.7 2.6 6.9 2.3]
 [5.1 3.3 1.7 0.5]
 [6.5 3.  5.5 1.8]
 [7.1 3.  5.9 2.1]
 [4.8 3.4 1.9 0.2]
 [5.7 2.6 3.5 1. ]
 [5.2 3.5 1.5 0.2]
 [6.1 3.  4.6 1.4]
 [5.7 2.9 4.2 1.3]
 [6.2 2.8 4.8 1.8]
 [7.7 3.8 6.7 2.2]
 [5.5 2.3 4.  1.3]
 [5.6 2.5 3.9 1.1]
 [7.2 3.6 6.1 2.5]
 [5.6 3.  4.5 1.5]
 [7.  3.2 4.7 1.4]
 [7.7 3.  6.1 2.3]
 [6.4 3.2 4.5 1.5]
 [5.1 3.8 1.5 0.3]
 [6.3 2.5 4.9 1.5]
 [5.1 3.8 1.9 0.4]
 [7.2 3.2 6.  1.8]
 [5.4 3.  4.5 1.5]
 [5.6 2.8 4.9 2. ]
 [6.3 3.3 4.7 1.6]
 [5.  3.6 1.4 0.2]
 [5.5 2.4 3.8 1.1]
 [6.  2.2 4.  1. ]
 [4.7 3.2 1.3 0.2]
 [5.9 3.2 4.8 1.8]]


In [77]:
arr = [4.7,3.0,6.9,2.2]
arr = np.array(arr)
arr

array([4.7, 3. , 6.9, 2.2])

In [78]:
def find(d , val , m , inverse):
    tr = (val - m).T
    tr = (-0.5) * tr
    
    dd =  ((2*3.14)**4)*d
    dd = 1/ dd 
    dd = dd **(1/2)
    
    s = val - m
    o = np.dot((inverse),(s))
    o.reshape(4,1)
    
    o = np.dot(tr.T , o)
    ans = 2.718 ** o
        
    return dd * ans

In [79]:
check = []
size = 149 * (0.3)
size = int(size)
size += 1

#finding the mean
m = np.mean(nu,axis=0)

for i in range(0,size):
    p1 = find(det[0] , arr , m[0] , inverse[0])
    p1 *= 1/3
    
    p2 = find(det[1] , arr , m[1] , inverse[1])
    p2*=1/3
    
    p3 = find(det[2] , arr , m[2] , inverse[2])
    p3*=1/3
    
    if p1 > p2 and p1 > p3:
        check.append(0)
    
    if p2 > p1 and p2 > p3:
        check.append(1)

    if p3 > p1 and p3 > p2:
        check.append(2)
print(check)  

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


In [80]:
add = 0
for i in range(0,45):
    if check[i] == y_test[i]:
        add = add + 1 
add

17

In [85]:
score *= 100
print("Accuracy of the built-in function:\n" , score*100)

print("----------------------------------")

accuracy = add/len(y_test)
accuracy *= 100
print("Accuracy wthout using built-in function:\n" , accuracy)

Accuracy of the built-in function:
 9111.111111111111
----------------------------------
Accuracy wthout using built-in function:
 37.77777777777778


#### The accuarcy is better after using the built-in function, so it is better to use that