In [86]:
import numpy as np
from numpy import random

# Create a numpy array of int, characters, float and find their shapes

In [87]:
arr = np.array([1, 2, 3, 4,5])
print(arr)
print("---------------------")
print(arr.shape)

[1 2 3 4 5]
---------------------
(5,)


In [88]:
arrc = np.array(['a', 'b', 'c', 'd','e'])
print(arrc)
print("---------------------")
print(arrc.shape)

['a' 'b' 'c' 'd' 'e']
---------------------
(5,)


In [89]:
arr3 = np.array([2.1,6.3,4.7,3.6])
print(arr3)
print("---------------------")
print(arr3.shape)

[2.1 6.3 4.7 3.6]
---------------------
(4,)


# Create a zeros, empty, identity , eye and a full array

In [90]:
arrz = np.zeros((2,3), dtype=int, order='C')
print(arrz)

[[0 0 0]
 [0 0 0]]


In [91]:
arre = np.empty((2,3), dtype = int, order='C')
print(arre)

[[0 0 0]
 [0 0 0]]


In [92]:
arri = np.identity(2, dtype = int)
arri

array([[1, 0],
       [0, 1]])

In [93]:
arre2 = np.eye(9,k = 3, dtype = int) #k is the diagnol
arre2

array([[0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [94]:
arrf = np.full([4, 2],11, dtype = int)
print(arrf)

[[11 11]
 [11 11]
 [11 11]
 [11 11]]


# Declare an array having the datatype of object, is it possible?

In [95]:
arro = np.empty((2,3), dtype = object) 
print(arro)

[[None None None]
 [None None None]]


#### Yes, it is possible

# Create an array having 5 equally spaced numbers ranging from 5 to 15

In [96]:
arrs = np.linspace(5, 15, num = 5, dtype = int)
arrs

array([ 5,  7, 10, 12, 15])

# Create a numpy array ranging from 1 to 100.

In [97]:
arr2 = np.arange(1,101, dtype= int)
arr2

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

# Reshape the above array into (100,15). Is it possible?
#### It is not possible

# Reshape the array into (100,10).
#### It is not possible.

# Flatten and ravel the reshaped array. What is the difference?

In [98]:
arrfl = np.reshape(arr2,(10,-1))
print(arrfl.flatten())
print(arrfl.flatten().shape)
print("-------------------------")
print(arrfl.ravel())
print(arrfl.ravel().shape)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
(100,)
-------------------------
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
(100,)


#### Ravel and flatten both convert multidimensional array  into one dimensional array. Ravel is faster than flatten which is only limited to numpy arrays.

# Take an array [[1 2 3] [4 5 6] [ 7 8 9]]. Sum it along 0 and 1 axis

In [99]:
arra = np.array([[1, 2, 3], [4, 5, 6], [ 7, 8, 9]])
arrsum = np.sum(arra,axis = 0)
print(arrsum)
print("---------------------")
arrsum2 = np.sum(arra,axis = 1)
print(arrsum2)

[12 15 18]
---------------------
[ 6 15 24]


# Find the number of bytes used by your array

In [100]:
print(arra.nbytes)

36


# Find the maximum and minimum values in a 1D array.

In [101]:
arr = np.array([1, 8, 7, 2, 5])
print(np.max(arr))

8


In [102]:
print(np.min(arr))

1


# Find the maximum and minimum values in 2D array

In [103]:
print(np.max(arra))

9


In [104]:
print(np.min(arra))

1


# Sort an array

In [105]:
print(np.sort(arr))

[1 2 5 7 8]


# Is * and mul the same as dot product for numpy arrays and matrices? Check.

In [120]:
a1 = np.random.randint(1,5, size=(5))
a2 = np.random.randint(1,5,size = (5))
ans = a1* a2
print(ans)
print("-----------------------------")
ans2 = np.multiply(a1,a2)
print(ans2)
print("-----------------------------")
a = [1,12,5,7]
b = [9,0,2,5]
a = np.array(a)
b = np.array(b)
ans3 = np.dot(a.T, b)
print(ans3)
print("-----------------------------")

[ 2 12  8  4  1]
-----------------------------
[ 2 12  8  4  1]
-----------------------------
54
-----------------------------


#### They are not the same

# Take the square root and norm of an array.

In [121]:
arrsq = np.sqrt([9, 4,  16])
arrsq

array([3., 2., 4.])

In [122]:
norma = np.linalg.norm(arr2)
print(norma)

5.477225575051661


# Find the std, non-zero, zero values and mean of an array.

In [123]:
arr = random.randint(15, size = (7))
arr

array([10,  0,  6,  2, 10,  2, 12])

In [124]:
st = np.std(arr)
print(st)
print("--------------")
nzer = np.nonzero(arr)
print(nzer)
print("--------------")
arr2 = np.array([1,0,2,0,5])
ze = np.where(arr2 == 0)[0]
print(zer)

4.4077853201547175
--------------
(array([0, 2, 3, 4, 5, 6], dtype=int64),)
--------------
(array([0, 1, 2, 3, 4, 5, 6], dtype=int64),)


# Convert some angles to radians and vice versa.

In [127]:
rad = np.radians(90)
ang = np.rad2deg(rad)
print(rad, ang)

1.5707963267948966 90.0


# Save and load some of your arrays

In [125]:
np.savetxt("lab10.txt", arr2)
ld = np.loadtxt("lab10.txt")
print(arr2 == ld)

[ True  True  True  True  True]


# Calculate the mean, std, var, max, min, of an array with shape (3,3,12,3) containing floats drawn from a normal distribution with mean 21 and sigma 4.5. see the np.random.normal.

In [129]:
mean, std = 12, 3.5
x = np.random.normal(loc = mean, scale = std, size= (3,3,12,3))
print(x)

[[[[ 8.90112831 10.77111336 10.43338126]
   [11.62057759 12.55073024 11.04511518]
   [ 9.66066173 13.14110725  9.41642252]
   [ 8.47857995 16.20482538  8.27447401]
   [ 5.26247686  7.64934896 13.66743461]
   [10.44919983 13.45458322 12.23630714]
   [11.7394282   7.45931329 13.54581368]
   [10.13234201 16.45826207  7.76286955]
   [14.82635371  7.06474694 10.21574808]
   [15.13773602 13.42923746 15.0483404 ]
   [16.04474364  6.19818513 11.18240753]
   [ 8.8891591   5.07452652 11.71714679]]

  [[15.82341716 10.87824727 11.05652202]
   [16.9983634  11.57234087 11.79880531]
   [ 6.92963191 16.40981294  8.3261568 ]
   [ 5.09402851 22.35047168 12.94687412]
   [19.20525345 14.11352082  9.79410004]
   [ 4.96545617 10.29394483 16.51219845]
   [15.35576834 14.4989356  13.68304403]
   [10.09769891  7.392948    4.29749927]
   [ 9.91349572 12.75250913 11.68247983]
   [14.37757238 11.59483832  9.75714818]
   [19.07315617 13.86457996 11.64306506]
   [ 7.2612553   7.14440551 12.79128173]]

  [[14.27802

In [130]:
print(np.mean(x))

<built-in method mean of numpy.ndarray object at 0x000001693810B510>


In [131]:
print(np.std(x))

3.2976817873823694


In [132]:
print(np.var(x))

10.87470517083338


In [134]:
print(np.min(x))

4.297499271461147


In [135]:
print(np.max(x))

22.350471682280343
